// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StationeryWeek3.Mvc.Data;

#nullable disable

namespace StationeryWeek3.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615143948_AddSupplierCode")]
    partial class AddSupplierCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Thiên Long"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hồng Hà"
                        },
                        new
                        {
                            Id = 3,
                            Name = "FlexOffice"
                        });
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bút"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vở"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dụng cụ"
                        });
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.Stationery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Stationeries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Code = "ST001",
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 10,
                            Name = "Bút bi Thiên Long",
                            Price = 5000m,
                            Quantity = 50,
                            SupplierCode = "SUP001"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CategoryId = 2,
                            Code = "ST002",
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 10,
                            Name = "Vở 200 trang",
                            Price = 18000m,
                            Quantity = 8,
                            SupplierCode = "SUP002"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            CategoryId = 3,
                            Code = "ST003",
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 10,
                            Name = "Thước kẻ 30cm",
                            Price = 12000m,
                            Quantity = 40,
                            SupplierCode = "SUP003"
                        });
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.StockIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StockIssues");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.StockIssueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StationeryId")
                        .HasColumnType("int");

                    b.Property<int>("StockIssueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationeryId");

                    b.HasIndex("StockIssueId");

                    b.ToTable("StockIssueItems");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.Stationery", b =>
                {
                    b.HasOne("StationeryWeek3.Mvc.Models.Brand", "Brand")
                        .WithMany("Stationeries")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StationeryWeek3.Mvc.Models.Category", "Category")
                        .WithMany("Stationeries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.StockIssueItem", b =>
                {
                    b.HasOne("StationeryWeek3.Mvc.Models.Stationery", "Stationery")
                        .WithMany()
                        .HasForeignKey("StationeryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StationeryWeek3.Mvc.Models.StockIssue", "StockIssue")
                        .WithMany("Items")
                        .HasForeignKey("StockIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stationery");

                    b.Navigation("StockIssue");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.Brand", b =>
                {
                    b.Navigation("Stationeries");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.Category", b =>
                {
                    b.Navigation("Stationeries");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.StockIssue", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
