// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StationeryWeek3.Mvc.Data;

#nullable disable

namespace StationeryWeek3.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614154351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.Stationery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Stationeries");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.StockIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StockIssues");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.StockIssueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StationeryId")
                        .HasColumnType("int");

                    b.Property<int>("StockIssueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationeryId");

                    b.HasIndex("StockIssueId");

                    b.ToTable("StockIssueItems");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.Stationery", b =>
                {
                    b.HasOne("StationeryWeek3.Mvc.Models.Brand", null)
                        .WithMany("Stationeries")
                        .HasForeignKey("BrandId");

                    b.HasOne("StationeryWeek3.Mvc.Models.Category", null)
                        .WithMany("Stationeries")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.StockIssueItem", b =>
                {
                    b.HasOne("StationeryWeek3.Mvc.Models.Stationery", "Stationery")
                        .WithMany()
                        .HasForeignKey("StationeryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StationeryWeek3.Mvc.Models.StockIssue", "StockIssue")
                        .WithMany("Items")
                        .HasForeignKey("StockIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stationery");

                    b.Navigation("StockIssue");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.Brand", b =>
                {
                    b.Navigation("Stationeries");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.Category", b =>
                {
                    b.Navigation("Stationeries");
                });

            modelBuilder.Entity("StationeryWeek3.Mvc.Models.StockIssue", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
